// src/components/home/aboutUs.tsx
import Link from "next/link";

import LottieAnimation from "@/components/lotties";

import teamLottie from "../../assets/lotties/team.json";

export default function AboutUs() {
  return (
    <div className="container mx-auto max-w-screen-lg px-6 py-0 sm:pt-6 sm:pb-4">
      <div className="items-center justify-center md:flex">
        <div className="mt-6 flex w-full items-center justify-center p-8 lg:mt-0 lg:w-1/2">
          <LottieAnimation
            animationData={teamLottie}
            width={400}
            height={400}
          />
        </div>

        <div className="h-full w-full p-2 lg:max-w-2xl">
          <h1 className="w-full py-4 pt-6 text-left text-4xl font-black subpixel-antialiased sm:text-center sm:text-3xl md:py-3 md:text-3xl lg:text-4xl">
            About Us
          </h1>

          <p className=" mt-2 mb-6 w-full text-left font-asap text-xl text-black sm:text-center  md:my-2 md:text-lg">
            FAIR Data Innovations Hub is a division of the California Medical
            Innovations Institute (CalMI<sup>2</sup>), a non profit biomedical
            research organization located in San Diego, California. We have a
            multidisciplinary team of enthusiasts about FAIR Data practices and
            software development.
          </p>
          <div className="flex w-full justify-center py-5">
            <a
              href="https://calmi2.org/"
              target="_blank"
              className="hidden"
              rel="noreferrer"
            ></a>
            <Link href="/team" passHref>
              <button
                type="button"
                className="w-max-content rounded-md border-none bg-black px-6 py-4 text-center text-base font-semibold text-white ring-2 ring-transparent ring-offset-2 transition duration-200 ease-in-out hover:ring-pink-600 focus:ring-pink-600"
              >
                Meet our team
              </button>
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}

// src/components/HomePage/AboutUs.vue
<template>
  <div
    class="container px-6 py-0 sm:pt-6 sm:pb-4 max-w-screen-xl mx-auto"
    :id="id"
  >
    <div class="items-center sm:flex">
      <div
        class="
          flex
          items-center
          justify-center
          w-full
          mt-6
          lg:mt-0 lg:w-1/2
          p-2
        "
      >
        <img
          class="w-full h-full lg:max-w-2xl"
          src="../../assets/udDesignInspiration.svg"
          alt="Catalogue-pana.svg"
        />
      </div>

      <div class="w-full lg:w-1/2 lg:max-w-2xl h-full p-2">
        <h1
          class="
            pt-6
            md:py-3
            w-full
            font-sans font-black
            text-black
            dark:text-white
            text-4xl
            sm:text-3xl
            md:text-3xl
            lg:text-4xl
            subpixel-antialiased
            text-left
            sm:text-center
          "
        >
          About Us
        </h1>

        <p
          class="
            my-2
            w-full
            font-sans
            text-left
            sm:text-center
            text-xl
            sm:text-base
            md:text-lg
            lg:text-xl
            text-black
            dark:text-white
          "
        >
          We are a team of researchers from the Caliornia Medical Innovations
          Institute who believe that all scientific research data should be
          curated and shared according to applicable standards on the FAIR Data
          Principles. We also believe that doing so should be easy for the
          researchers collecting that data.
        </p>
        <div class="flex w-full justify-center py-5">
          <router-link to="/team">
            <button
              type="button"
              class="
                py-4
                px-6
                bg-primary
                hover:bg-blue-600
                focus:ring-indigo-500 focus:ring-offset-indigo-200
                text-white
                w-max-content
                transition
                ease-in
                duration-200
                text-center text-base
                font-semibold
                shadow-md
                focus:outline-none focus:ring-2 focus:ring-offset-2
                rounded-lg
              "
            >
              Meet the team
            </button>
          </router-link>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default { name: "AboutUs", props: ["id"] };
</script>

<style></style>
