// src/components/project/projectCard.tsx
import { Icon } from '@iconify/react';
import Image, { type StaticImageData } from 'next/image';
import Link from 'next/link';
import React from 'react';

export type ProjectImage = {
  src: string | StaticImageData;
  alt: string;
  width?: number;
  height?: number;
  contain?: boolean;
};

export type Project = {
  slug: string; // ex: '/projects/codefair'
  title: string;
  subtitle?: string;
  description: string;
  image: ProjectImage;
  badges?: string[];
};

export default function ProjectCard({ project }: { project: Project }) {
  const { slug, title, subtitle, description, image, badges } = project;

  return (
    <Link
      href={slug}
      className="group block touch-manipulation focus:outline-none"
      aria-label={`${title} - open project`}
    >
      <article
        className="relative grid h-full min-h-[28rem] overflow-hidden rounded-xl border border-stone-200 bg-white/90 shadow-sm transition-all duration-300 hover:border-pink-300"
        style={{ gridTemplateRows: `auto 1fr` }}
      >
        <div className="relative h-44 w-full overflow-hidden bg-gradient-to-b from-stone-50 to-white dark:from-stone-900 dark:to-stone-900">
          <div
            aria-hidden
            className="pointer-events-none absolute inset-0 opacity-0 transition-opacity duration-300 group-hover:opacity-100"
          >
            <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,rgba(0,0,0,0.08)_0%,rgba(0,0,0,0)_60%)]" />
          </div>

          <div className="relative h-full w-full p-3">
            <Image
              src={image.src}
              alt={image.alt}
              fill
              sizes="(min-width: 768px) 33vw, 100vw"
              className={[
                `h-full w-full object-contain pt-4`,
                `scale-[.95] transform-gpu transition-transform duration-300`,
                `group-hover:scale-100 group-focus:scale-100`,
              ].join(` `)}
              draggable={false}
              priority={false}
            />
          </div>
        </div>

        <div className="flex flex-1 flex-col gap-2 p-4">
          <h3 className="group-active:text-primary text-lg font-semibold text-stone-900 transition-colors group-hover:text-stone-950 dark:text-stone-100 dark:group-hover:text-white dark:group-active:text-white">
            {title}
          </h3>

          {subtitle && (
            <p className="text-sm font-medium text-stone-600 dark:text-stone-300">
              {subtitle}
            </p>
          )}

          <p className="font-asap text-sm leading-6 text-stone-700 dark:text-stone-300">
            {description}
          </p>

          {!!badges?.length && (
            <div className="mt-1 flex flex-wrap gap-1.5">
              {badges.map((b) => (
                <span
                  key={b}
                  className="rounded border border-pink-300/70 bg-pink-50 px-2 py-0.5 text-[11px] text-pink-700 transition-colors group-hover:border-pink-400 group-active:border-pink-400 dark:border-stone-700 dark:text-stone-300"
                >
                  {b}
                </span>
              ))}
            </div>
          )}

          <div className="mt-auto flex pt-2">
            <div className="relative ml-auto inline-flex items-center gap-2 pl-1">
              <span className="group-hover:text-primary group-active:text-primary text-xs text-stone-500 transition-colors dark:text-stone-400">
                Learn more
              </span>
              <Icon
                icon="solar:arrow-right-broken"
                className="group-hover:text-primary group-active:text-primary h-4 w-4 transition-colors"
                aria-hidden="true"
              />
              <span className="bg-primary absolute -bottom-1 left-1/2 h-[2px] w-0 transition-all duration-300 group-hover:left-0 group-hover:w-full group-active:left-0 group-active:w-full" />
            </div>
          </div>
        </div>
      </article>
    </Link>
  );
}

// src/components/HomePage/ProjectCard.vue
<template>
  <div class="w-full h-full flex justify-center items-center">
    <div class="w-full h-full flex justify-center items-center">
      <div
        class="
          flex
          w-4/5
          mx-auto
          overflow-hidden
          bg-gray-100
          rounded-lg
          shadow-lg
          dark:bg-gray-700
          justify-center
        "
        style="height: 75%"
      >
        <div class="w-full flex flex-col justify-evenly">
          <div class="w-full">
            <h1
              class="text-center font-sans text-3xl text-black dark:text-white"
            >
              <strong>
                <slot name="title">Project Title</slot>
              </strong>
            </h1>
          </div>

          <div class="flex justify-evenly mt-2 p-5">
            <!-- <div
              class="w-1/3 h-full bg-cover"
              :style="`background-image:url(${projectImage})`"
            ></div> -->
            <div class="w-1/3 h-full flex justify-center items-center">
              <img
                :src="projectImage"
                alt=""
                class="w-full h-auto rounded-lg"
              />
            </div>
            <div
              class="w-2/3 p-4 md:p-1 md:ml-3 flex justify-center items-center"
            >
              <p class="text-sm text-black dark:text-white">
                <slot name="description">Project description</slot>
              </p>
            </div>
          </div>

          <div class="w-full">
            <h2
              class="text-center font-sans text-xl text-black dark:text-white"
            >
              <strong> <slot name="subtitle">Project SubTitle</slot> </strong>
            </h2>
          </div>

          <div class="w-5/6 mx-auto flex justify-evenly">
            <button v-for="item in actionButtons" :key="item.name">
              <router-link
                :to="item.href"
                class="
                  py-2
                  px-4
                  bg-indigo-600
                  hover:bg-indigo-700
                  focus:ring-indigo-500 focus:ring-offset-indigo-200
                  text-white
                  transition
                  ease-in
                  duration-200
                  text-center text-base
                  font-semibold
                  shadow-md
                  focus:outline-none focus:ring-2 focus:ring-offset-2
                  rounded-lg
                "
              >
                {{ item.name }}
              </router-link>
            </button>
          </div>
          <div class="flex w-full justify-center mt-3 item-center">
            <router-link
              :to="learnMoreLink"
              class="
                px-2
                py-1
                text-xs
                font-bold
                text-white
                uppercase
                transition-colors
                duration-200
                transform
                bg-gray-800
                rounded-md
                dark:bg-gray-700
                hover:bg-gray-700
                dark:hover:bg-gray-600
                focus:outline-none focus:bg-gray-700
                dark:focus:bg-gray-600
              "
            >
              <slot name="moreInfo">Learn More</slot>
            </router-link>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "ProjectCard",
  props: ["projectImage", "actionButtons", "learnMoreLink"],
};
</script>

<style lang="postcss" scoped></style>
