// src/pages/privacypolicy.tsx
import Head from "next/head";

import Link from "next/link";

export default function PrivacyPolicy() {
  return (
    <div>
      <Head>
        <title>Privacy Policy - Fair Data Innovations Hub</title>
        <meta
          property="og:title"
          content="Privacy Policy - Fair Data Innovations Hub"
        />
        <meta
          property="twitter:title"
          content="Privacy Policy - Fair Data Innovations Hub"
        />

        <link rel="canonical" href="https://fairdataihub.org/privacypolicy" />
        <meta
          property="og:url"
          content="https://fairdataihub.org/privacypolicy"
        />
        <meta
          property="twitter:url"
          content="https://fairdataihub.org/privacypolicy"
        />

        <meta
          name="description"
          content="View the Privacy Policy of fairdataihub.org"
        />
        <meta
          property="og:description"
          content="View the Privacy Policy of fairdataihub.org"
        />
        <meta
          property="twitter:description"
          content="View the Privacy Policy of fairdataihub.org"
        />

        <meta
          property="og:image"
          content="https://fairdataihub.org/thumbnails/index.png"
        />
        <meta
          property="twitter:image"
          content="https://fairdataihub.org/thumbnails/index.png"
        />
      </Head>

      <main>
        <section className="mx-auto flex max-w-screen-lg flex-col px-6 py-5 text-lg text-black sm:px-6 lg:px-8">
          <h1 className="heading">Privacy Policy</h1>

          <p className="content">Effective Date: December 01, 2021</p>

          <p className="content">
            At Fair Data Innovations Hub, accessible from
            <Link href="/" passHref>
              <span className="text-url cursor-pointer text-base">
                &nbsp;https://fairdataihub.org/
              </span>
            </Link>
            , one of our main priorities is the privacy of our visitors. This
            Privacy Policy document contains types of information that is
            collected and recorded by Fair Data Innovations Hub and how we use
            it.
          </p>

          <p className="content">
            If you have additional questions or require more information about
            our Privacy Policy, do not hesitate to contact us.
          </p>

          <p className="content">
            This Privacy Policy applies only to our online activities and is
            valid for visitors to our website with regards to the information
            that they shared and/or collect in Fair Data Innovations Hub. This
            policy is not applicable to any information collected offline or via
            channels other than this website.
          </p>

          <h2 className="subheading">Consent</h2>

          <p className="content">
            By using our website, you hereby consent to our Privacy Policy and
            agree to its terms.
          </p>

          <h2 className="subheading">Information we collect</h2>

          <p className="content">
            The personal information that you are asked to provide, and the
            reasons why you are asked to provide it, will be made clear to you
            at the point we ask you to provide your personal information.
          </p>
          <p className="content">
            If you contact us directly, we may receive additional information
            about you such as your name, email address, phone number, the
            contents of the message and/or attachments you may send us, and any
            other information you may choose to provide.
          </p>
          <p className="content">
            When you register for an Account, we may ask for your contact
            information, including items such as name, company name, address,
            email address, and telephone number.
          </p>

          <h2 className="subheading">How we use your information</h2>

          <p className="content">
            We use the information we collect in various ways, including to:
          </p>

          <div className="pl-8">
            <ul className="my-1 list-outside list-disc pb-3 text-base leading-7 text-gray-800">
              <li>Provide, operate, and maintain our website</li>
              <li>Improve, personalize, and expand our website</li>
              <li>Understand and analyze how you use our website</li>
              <li>
                Develop new products, services, features, and functionality
              </li>
              <li>
                Communicate with you, either directly or through one of our
                partners, including for customer service, to provide you with
                updates and other information relating to the website, and for
                marketing and promotional purposes
              </li>
              <li>Send you emails</li>
              <li>Find and prevent fraud</li>
            </ul>
          </div>

          <h2 className="subheading">Log Files</h2>

          <p className="content">
            Fair Data Innovations Hub follows a standard procedure of using log
            files. These files log visitors when they visit websites. All
            hosting companies do this and a part of hosting services&apos;
            analytics. The information collected by log files include internet
            protocol (IP) addresses, browser type, Internet Service Provider
            (ISP), date and time stamp, referring/exit pages, and possibly the
            number of clicks. These are not linked to any information that is
            personally identifiable. The purpose of the information is for
            analyzing trends, administering the site, tracking users&apos;
            movement on the website, and gathering demographic information.
          </p>

          <h2 className="subheading">Cookies and Web Beacons</h2>

          <p className="content">
            Like any other website, Fair Data Innovations Hub uses
            &apos;cookies&apos;. These cookies are used to store information
            including visitors&apos; preferences, and the pages on the website
            that the visitor accessed or visited. The information is used to
            optimize the users&apos; experience by customizing our web page
            content based on visitors&apos; browser type and/or other
            information.
          </p>

          <p className="content">
            FAIR Data Innovations Hub may also collect data automatically
            through cookies. For information on how we use cookies, refer to our
            <Link href="/cookiepolicy" passHref>
              <span className="text-url cursor-pointer text-base">
                &nbsp;Cookie Policy
              </span>
            </Link>
            .
          </p>

          <h2 className="subheading">Advertising Partners Privacy Policies</h2>

          <p className="content">
            You may consult this list to find the Privacy Policy for each of the
            advertising partners of Fair Data Innovations Hub.
          </p>

          <p className="content">
            Third-party ad servers or ad networks uses technologies like
            cookies, JavaScript, or Web Beacons that are used in their
            respective advertisements and links that appear on Fair Data
            Innovations Hub, which are sent directly to users&apos; browser.
            They automatically receive your IP address when this occurs. These
            technologies are used to measure the effectiveness of their
            advertising campaigns and/or to personalize the advertising content
            that you see on websites that you visit.
          </p>

          <p className="content">
            Note that Fair Data Innovations Hub has no access to or control over
            these cookies that are used by third-party advertisers.
          </p>

          <h2 className="subheading">Third Party Privacy Policies</h2>

          <p className="content">
            Fair Data Innovations Hub&apos;s Privacy Policy does not apply to
            other advertisers or websites. Thus, we are advising you to consult
            the respective Privacy Policies of these third-party ad servers for
            more detailed information. It may include their practices and
            instructions about how to opt-out of certain options.
          </p>

          <p className="content">
            You can choose to disable cookies through your individual browser
            options. To know more detailed information about cookie management
            with specific web browsers, it can be found at the browsers&apos;
            respective websites.
          </p>

          <h2 className="subheading">CCPA Privacy Rights</h2>

          <p className="content">
            Under the CCPA, among other rights, California consumers have the
            right to:
          </p>

          <div className="pl-8">
            <ul className="my-1 list-outside list-disc pb-3 text-base leading-7 text-gray-800">
              <li>
                Request that a business that collects a consumer&apos;s personal
                data disclose the categories and specific pieces of personal
                data that a business has collected about consumers.
              </li>
              <li>
                Request that a business delete any personal data about the
                consumer that a business has collected.
              </li>
              <li>
                Request that a business that sells a consumer&apos;s personal
                data, not sell the consumer&apos;s personal data.
              </li>
              <li>
                If you make a request, we have one month to respond to you. If
                you would like to exercise any of these rights, please contact
                us.
              </li>
            </ul>
          </div>

          <h2 className="subheading">GDPR Data Protection Rights</h2>

          <p className="content">
            We would like to make sure you are fully aware of all of your data
            protection rights. Every user is entitled to the following:
          </p>

          <div className="pl-8">
            <ul className="my-1 list-outside list-disc pb-3 text-base leading-7 text-gray-800">
              <li>
                <span className="italic"> The right to access </span>– You have
                the right to request copies of your personal data. We may charge
                you a small fee for this service.
              </li>
              <li>
                <span className="italic"> The right to rectification </span> –
                You have the right to request that we correct any information
                you believe is inaccurate. You also have the right to request
                that we complete the information you believe is incomplete.
              </li>
              <li>
                <span className="italic"> The right to erasure </span> – You
                have the right to request that we erase your personal data,
                under certain conditions.
              </li>
              <li>
                <span className="italic">
                  {` `}
                  The right to restrict processing
                </span>
                – You have the right to request that we restrict the processing
                of your personal data, under certain conditions.
              </li>
              <li>
                <span className="italic">
                  {` `}
                  The right to object to processing{` `}
                </span>
                {` `}– You have the right to object to our processing of your
                personal data, under certain conditions.
              </li>
              <li>
                <span className="italic"> The right to data portability </span>
                {` `}– You have the right to request that we transfer the data
                that we have collected to another organization, or directly to
                you, under certain conditions.
              </li>
            </ul>
          </div>

          <p className="content">
            If you make a request, we have one month to respond to you. If you
            would like to exercise any of these rights, please contact us.
          </p>

          <h2 className="subheading">Children&apos;s Information</h2>

          <p className="content">
            Another part of our priority is adding protection for children while
            using the internet. We encourage parents and guardians to observe,
            participate in, and/or monitor and guide their online activity.
          </p>

          <p className="content">
            Fair Data Innovations Hub does not knowingly collect any Personal
            Identifiable Information from children under the age of 13. If you
            think that your child provided this kind of information on our
            website, we strongly encourage you to contact us immediately and we
            will do our best efforts to promptly remove such information from
            our records.
          </p>

          <h2 className="subheading">Privacy policy changes</h2>

          <p className="content">
            Just as our business changes constantly, this Privacy Policy may
            also change from time to time. If you want to see changes made to
            this Privacy Policy from time to time, we invite you to access this
            Privacy Policy to see the changes. If we make material changes or
            changes that will have an impact on you (e.g. when we start
            processing your personal information for other purposes than set out
            above), we will contact you prior to commencing that processing.
          </p>

          <p className="content">
            Any material changes made will be notified to you via our Sites or
            by email, to the extent possible, three (3) business days at least
            before any changes come into force.
          </p>

          <h2 className="subheading">Questions and complaints</h2>

          <p className="content">
            Please feel free to contact us if you have any questions or
            complaints about Fair Data Innovation Hub&apos;s Privacy Policy or
            practices.
          </p>

          <p className="content">
            <strong> Address: </strong> 11107 Roselle St. Ste #211 San Diego, CA
            92121
          </p>

          <p className="content">
            <strong> Contact form: </strong>
            <Link href="/contact-us" passHref>
              <span className="text-url cursor-pointer text-base">
                &nbsp;https://fairdataihub.org/contact-us
              </span>
            </Link>
          </p>

          <p className="content">
            <strong> Email: </strong>
            <a
              href="mailto:info@fairdataihub.org"
              className="text-url text-base"
            >
              info@fairdataihub.org
            </a>
          </p>
        </section>
      </main>
    </div>
  );
}

// pages/privacypolicy/index.vue
<template>
  <base-section class="">
    <Html>
      <Head>
        <Link
          rel="canonical"
          :href="`https://fairdataihub.org${$route.path}`"
        />
        <Title>Privacy Policy - Fair Data Innovations Hub</Title>
      </Head>
    </Html>

    <section
      class="text-black flex flex-col mx-auto max-w-screen-lg py-5 text-lg px-6 sm:px-6 lg:px-8"
    >
      <h1 class="heading">Privacy Policy for FAIR Data Innovations Hub</h1>

      <p>Effective Date: December 01, 2021</p>

      <p>
        At Fair Data Innovations Hub, accessible from
        <NuxtLink to="/" class="text-url text-base">
          https://fairdataihub.org/ </NuxtLink
        >, one of our main priorities is the privacy of our visitors. This
        Privacy Policy document contains types of information that is collected
        and recorded by Fair Data Innovations Hub and how we use it.
      </p>

      <p>
        If you have additional questions or require more information about our
        Privacy Policy, do not hesitate to contact us.
      </p>

      <p>
        This Privacy Policy applies only to our online activities and is valid
        for visitors to our website with regards to the information that they
        shared and/or collect in Fair Data Innovations Hub. This policy is not
        applicable to any information collected offline or via channels other
        than this website.
      </p>

      <h2 class="subheading">Consent</h2>

      <p>
        By using our website, you hereby consent to our Privacy Policy and agree
        to its terms.
      </p>

      <h2 class="subheading">Information we collect</h2>

      <p>
        The personal information that you are asked to provide, and the reasons
        why you are asked to provide it, will be made clear to you at the point
        we ask you to provide your personal information.
      </p>
      <p>
        If you contact us directly, we may receive additional information about
        you such as your name, email address, phone number, the contents of the
        message and/or attachments you may send us, and any other information
        you may choose to provide.
      </p>
      <p>
        When you register for an Account, we may ask for your contact
        information, including items such as name, company name, address, email
        address, and telephone number.
      </p>

      <h2 class="subheading">How we use your information</h2>

      <p>We use the information we collect in various ways, including to:</p>

      <div class="pl-8">
        <ul
          class="list-disc list-outside pb-3 my-1 text-base leading-7 text-gray-800"
        >
          <li>Provide, operate, and maintain our website</li>
          <li>Improve, personalize, and expand our website</li>
          <li>Understand and analyze how you use our website</li>
          <li>Develop new products, services, features, and functionality</li>
          <li>
            Communicate with you, either directly or through one of our
            partners, including for customer service, to provide you with
            updates and other information relating to the website, and for
            marketing and promotional purposes
          </li>
          <li>Send you emails</li>
          <li>Find and prevent fraud</li>
        </ul>
      </div>

      <h2 class="subheading">Log Files</h2>

      <p>
        Fair Data Innovations Hub follows a standard procedure of using log
        files. These files log visitors when they visit websites. All hosting
        companies do this and a part of hosting services' analytics. The
        information collected by log files include internet protocol (IP)
        addresses, browser type, Internet Service Provider (ISP), date and time
        stamp, referring/exit pages, and possibly the number of clicks. These
        are not linked to any information that is personally identifiable. The
        purpose of the information is for analyzing trends, administering the
        site, tracking users' movement on the website, and gathering demographic
        information.
      </p>

      <h2 class="subheading">Cookies and Web Beacons</h2>

      <p>
        Like any other website, Fair Data Innovations Hub uses 'cookies'. These
        cookies are used to store information including visitors' preferences,
        and the pages on the website that the visitor accessed or visited. The
        information is used to optimize the users' experience by customizing our
        web page content based on visitors' browser type and/or other
        information.
      </p>

      <p>
        FAIR Data Innovations Hub may also collect data automatically through
        cookies. For information on how we use cookies, refer to our
        <NuxtLink to="/cookiepolicy" class="text-url text-base">
          Cookie Policy </NuxtLink
        >.
      </p>

      <h2 class="subheading">Advertising Partners Privacy Policies</h2>

      <p>
        You may consult this list to find the Privacy Policy for each of the
        advertising partners of Fair Data Innovations Hub.
      </p>

      <p>
        Third-party ad servers or ad networks uses technologies like cookies,
        JavaScript, or Web Beacons that are used in their respective
        advertisements and links that appear on Fair Data Innovations Hub, which
        are sent directly to users' browser. They automatically receive your IP
        address when this occurs. These technologies are used to measure the
        effectiveness of their advertising campaigns and/or to personalize the
        advertising content that you see on websites that you visit.
      </p>

      <p>
        Note that Fair Data Innovations Hub has no access to or control over
        these cookies that are used by third-party advertisers.
      </p>

      <h2 class="subheading">Third Party Privacy Policies</h2>

      <p>
        Fair Data Innovations Hub's Privacy Policy does not apply to other
        advertisers or websites. Thus, we are advising you to consult the
        respective Privacy Policies of these third-party ad servers for more
        detailed information. It may include their practices and instructions
        about how to opt-out of certain options.
      </p>

      <p>
        You can choose to disable cookies through your individual browser
        options. To know more detailed information about cookie management with
        specific web browsers, it can be found at the browsers' respective
        websites.
      </p>

      <h2 class="subheading">CCPA Privacy Rights</h2>

      <p>
        Under the CCPA, among other rights, California consumers have the right
        to:
      </p>

      <div class="pl-8">
        <ul
          class="list-disc list-outside pb-3 my-1 text-base leading-7 text-gray-800"
        >
          <li>
            Request that a business that collects a consumer's personal data
            disclose the categories and specific pieces of personal data that a
            business has collected about consumers.
          </li>
          <li>
            Request that a business delete any personal data about the consumer
            that a business has collected.
          </li>
          <li>
            Request that a business that sells a consumer's personal data, not
            sell the consumer's personal data.
          </li>
          <li>
            If you make a request, we have one month to respond to you. If you
            would like to exercise any of these rights, please contact us.
          </li>
        </ul>
      </div>

      <h2 class="subheading">GDPR Data Protection Rights</h2>

      <p>
        We would like to make sure you are fully aware of all of your data
        protection rights. Every user is entitled to the following:
      </p>

      <div class="pl-8">
        <ul
          class="list-disc list-outside pb-3 my-1 text-base leading-7 text-gray-800"
        >
          <li>
            <span class="italic"> The right to access </span>
            – You have the right to request copies of your personal data. We may
            charge you a small fee for this service.
          </li>
          <li>
            <span class="italic"> The right to rectification </span> – You have
            the right to request that we correct any information you believe is
            inaccurate. You also have the right to request that we complete the
            information you believe is incomplete.
          </li>
          <li>
            <span class="italic"> The right to erasure </span> – You have the
            right to request that we erase your personal data, under certain
            conditions.
          </li>
          <li>
            <span class="italic"> The right to restrict processing </span> – You
            have the right to request that we restrict the processing of your
            personal data, under certain conditions.
          </li>
          <li>
            <span class="italic"> The right to object to processing </span> –
            You have the right to object to our processing of your personal
            data, under certain conditions.
          </li>
          <li>
            <span class="italic"> The right to data portability </span> – You
            have the right to request that we transfer the data that we have
            collected to another organization, or directly to you, under certain
            conditions.
          </li>
        </ul>
      </div>

      <p>
        If you make a request, we have one month to respond to you. If you would
        like to exercise any of these rights, please contact us.
      </p>

      <h2 class="subheading">Children's Information</h2>

      <p>
        Another part of our priority is adding protection for children while
        using the internet. We encourage parents and guardians to observe,
        participate in, and/or monitor and guide their online activity.
      </p>

      <p>
        Fair Data Innovations Hub does not knowingly collect any Personal
        Identifiable Information from children under the age of 13. If you think
        that your child provided this kind of information on our website, we
        strongly encourage you to contact us immediately and we will do our best
        efforts to promptly remove such information from our records.
      </p>

      <h2 class="subheading">Privacy policy changes</h2>

      <p>
        Just as our business changes constantly, this Privacy Policy may also
        change from time to time. If you want to see changes made to this
        Privacy Policy from time to time, we invite you to access this Privacy
        Policy to see the changes. If we make material changes or changes that
        will have an impact on you (e.g. when we start processing your personal
        information for other purposes than set out above), we will contact you
        prior to commencing that processing.
      </p>

      <p>
        Any material changes made will be notified to you via our Sites or by
        email, to the extent possible, three (3) business days at least before
        any changes come into force.
      </p>

      <h2 class="subheading">Questions and complaints</h2>

      <p>
        Please feel free to contact us if you have any questions or complaints
        about Fair Data Innovation Hub's Privacy Policy or practices.
      </p>

      <p>
        <strong> Address: </strong> 11107 Roselle St. Ste #211 San Diego, CA
        92121
      </p>

      <p>
        <strong> Contact form: </strong>
        <NuxtLink to="/contact-us" class="text-url text-base">
          https://fairdataihub.org/contact-us
        </NuxtLink>
      </p>

      <p>
        <strong> Email: </strong>
        <a href="mailto:info@fairdataihub.org" class="text-url text-base">
          info@fairdataihub.org
        </a>
      </p>
    </section>
  </base-section>
</template>

<script>
export default {
  layout: "default",
  scrollToTop: true,
  mounted() {
    window.scrollTo(0, 0);
  },
};
</script>

<style lang="postcss" scoped>
.heading {
  @apply mb-3 mt-4 font-extrabold tracking-tight text-4xl;
}

.subheading {
  @apply mb-3 mt-6 font-bold tracking-tight text-3xl;
}

p {
  @apply my-1 text-base leading-7 text-gray-800 font-normal;
}
</style>
