// src/components/home/projectsCarousel.tsx
import { useState } from "react";
import { Swiper, SwiperSlide } from "swiper/react";
import { Autoplay, Navigation, Pagination, Thumbs, A11y } from "swiper";
import Link from "next/link";
import Image from "next/image";

import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/autoplay";
import "swiper/css/thumbs";

export default function ProjectsCarousel() {
  const thumbnails = [
    {
      src: `/images/carousel/sodasparc.png`,
      alt: `Navigate to SODA for SPARC card`,
      width: `150`,
      height: `50`,
    },
    {
      src: `/images/carousel/FAIRshare-full.png`,
      alt: `Navigate to FAIRshare card`,
      width: `200`,
      height: `40`,
    },
    {
      src: `/images/carousel/knowmore.png`,
      alt: `Navigate to Know More card`,
      width: `150`,
      height: `30`,
    },
    {
      src: `/images/carousel/sparclink.png`,
      alt: `Navigate to SPARClink card`,
      width: `150`,
      height: `40`,
    },
    {
      src: `/images/carousel/aqua.png`,
      alt: `Navigate to Aqua card`,
      width: `150`,
      height: `85`,
    },
  ];

  const projectsList = [
    {
      name: `SODA for SPARC`,
      imageUrl: `/images/carousel/sodasparc.png`,
      imageWidth: `320`,
      imageHeight: `103`,
      description: `SODA (Software to Organize Data Automatically) for SPARC is a desktop software intended to facilitate the data organization and submission process for SPARC investigators according to the FAIR SPARC data standards.`,
      page: `/sodaforsparc`,
    },
    {
      name: `FAIRshare`,
      imageUrl: `/images/carousel/FAIRshare-full.png`,
      imageWidth: `320`,
      imageHeight: `60`,
      description: `FAIRshare is a cross-platform desktop software that allows researchers to easily organize and share their biomedical research data and software according to applicable FAIR guidelines.`,
      page: `/fairshare`,
    },
    {
      name: `KnowMore`,
      imageUrl: `/images/carousel/knowmore.png`,
      imageWidth: `320`,
      imageHeight: `68`,
      description: `KnowMore is an automated knowledge discovery tool that allows users of the portal to visualize, in just a few clicks, potential similarities, differences, and connections between multiple SPARC datasets of their choice.`,
      page: `/knowmore`,
    },
    {
      name: `SPARClink`,
      imageUrl: `/images/carousel/sparclink.png`,
      imageWidth: `320`,
      imageHeight: `80`,
      description: `SPARClink is a system that queries publications using open source tools and platforms and create an interactable visualization that showcases the impact that SPARC and their FAIR data practices have in advancing the field of bioelectronic medicine.`,
      page: `/sparclink`,
    },
    {
      name: `AQUA`,
      imageUrl: `/images/carousel/aqua.png`,
      imageWidth: `320`,
      imageHeight: `177`,
      description: `AQUA (Advanced QUery Architecture for the SPARC Portal) improves the SPARC Portal by making the search engine smarter at understanding user search keywords, enhancing the result display, and providing users with better result filtering and sorting options.`,
      page: `/aqua`,
    },
  ];

  const [SwiperThumbs, setSwiperThumbs] = useState(null);

  return (
    <>
      <section>
        <div className="mx-auto h-auto w-full max-w-screen-lg px-4 pt-1 pb-3">
          <div className="mb-4 flex flex-col items-center justify-center">
            <h2 className="my-2 text-center text-4xl font-extrabold tracking-tight sm:text-4xl">
              Current Projects
            </h2>
            <p className="w-full max-w-2xl text-center font-asap text-xl">
              These are the projects we are working on at the moment:
            </p>
          </div>

          <Swiper
            modules={[Navigation, Pagination, Autoplay, Thumbs, A11y]}
            slidesPerView={1}
            navigation
            setWrapperSize={true}
            grabCursor={true}
            loop={true}
            autoplay={{
              delay: 6000,
              pauseOnMouseEnter: true,
              disableOnInteraction: false,
            }}
            mousewheel={{ releaseOnEdges: true }}
            thumbs={{
              swiper:
                SwiperThumbs && !SwiperThumbs[`destroyed`]
                  ? SwiperThumbs
                  : null,
            }}
            className="h-full"
          >
            {projectsList.map((project, index) => (
              <SwiperSlide
                key={index}
                className="my-auto flex h-full items-center justify-center py-10"
              >
                <section className="mx-10 my-auto flex h-full w-4/5 flex-row items-center justify-center rounded-lg px-5 py-10 text-gray-600 shadow-xl">
                  <div className="container mx-auto flex h-full flex-col items-center justify-center">
                    <div className="relative my-5 flex flex-row items-center justify-center sm:py-0 lg:max-w-lg">
                      <Image
                        className="relative"
                        src={project.imageUrl}
                        alt={project.name + ` logo`}
                        width={project.imageWidth}
                        height={project.imageHeight}
                      />
                    </div>
                    <div className="my-4 flex h-full flex-col items-center text-center sm:mb-16 md:mb-0">
                      <p className="w-full text-left font-asap text-base text-black sm:text-center md:text-base lg:text-lg">
                        {project.description}
                      </p>

                      <div className="flex w-full justify-center py-4">
                        <Link href={project.page} passHref>
                          <button className="inline-flex rounded border-0 bg-black px-6 py-2 text-lg text-white ring-2 ring-transparent ring-offset-2 transition hover:ring-pink-600 focus:outline-none focus:ring-pink-600 sm:ml-4 md:text-base lg:text-lg">
                            Learn more about {project.name}
                          </button>
                        </Link>
                      </div>
                    </div>
                  </div>
                </section>
              </SwiperSlide>
            ))}
          </Swiper>
          <Swiper
            slidesPerView={5}
            watchSlidesProgress={true}
            className="thumbs-swiper hidden sm:block"
            // @ts-expect-error will fix this later
            onSwiper={(swiper) => setSwiperThumbs(swiper)}
          >
            {thumbnails.map((thumbnail, index) => (
              <SwiperSlide virtualIndex={index} key={index}>
                <div className="thumbnail relative h-max w-max">
                  <Image
                    className="px-3 py-2"
                    src={thumbnail.src}
                    alt={thumbnail.alt}
                    width={thumbnail.width}
                    height={thumbnail.height}
                  />
                </div>
              </SwiperSlide>
            ))}
          </Swiper>
        </div>
      </section>
    </>
  );
}

// components/home/ProjectsCarousel.vue
<template>
  <div class="w-full max-w-screen-lg mx-auto h-auto pt-1 pb-3 px-4">
    <div class="flex flex-col justify-center items-center mb-4">
      <h2
        class="my-2 font-extrabold tracking-tight text-4xl sm:text-4xl text-center"
      >
        Current Projects
      </h2>
      <p class="w-full max-w-2xl text-xl font-asap text-center">
        These are the projects we are working on at the moment:
      </p>
    </div>

    <swiper
      :modules="modules"
      :slides-per-view="1"
      navigation
      :setWrapperSize="true"
      :grabCursor="true"
      :loop="true"
      :autoplay="{
        delay: 6000,
        pauseOnMouseEnter: true,
        disableOnInteraction: false,
      }"
      :thumbs="{ swiper: swiperThumbs }"
      :mousewheel="{ releaseOnEdges: true }"
      class="h-full"
    >
      <swiper-slide
        v-for="project in projectsList"
        :key="project.name"
        class="py-10 flex justify-center items-center h-full my-auto"
      >
        <section
          class="text-gray-600 w-4/5 h-full my-auto mx-10 px-5 py-10 flex flex-row justify-center items-center rounded-lg shadow-xl"
        >
          <div
            class="container mx-auto flex flex-col justify-center items-center h-full"
          >
            <div
              class="lg:max-w-lg my-5 sm:py-0 flex flex-row justify-center items-center"
            >
              <img
                class="object-cover object-center rounded sm:pt-20 md:pt-0 sm:h-full md:h-auto lg:h-auto sm:w-60 md:w-72 lg:w-80"
                alt="SODA for SPARC logo"
                :src="project.imageUrl"
              />
            </div>
            <div
              class="flex flex-col my-4 sm:mb-16 md:mb-0 items-center text-center h-full"
            >
              <p
                class="w-full text-left sm:text-center text-base md:text-base lg:text-lg font-asap text-black"
              >
                {{ project.description }}
              </p>

              <div class="w-full flex justify-center py-4">
                <NuxtLink :to="project.page">
                  <button
                    class="sm:ml-4 inline-flex border-0 py-2 px-6 focus:outline-none rounded text-lg md:text-base lg:text-lg transition bg-black text-white ring-2 ring-offset-2 ring-transparent hover:ring-pink-600 focus:ring-pink-600"
                  >
                    Learn more about {{ project.name }}
                  </button>
                </NuxtLink>
              </div>
            </div>
          </div>
        </section>
      </swiper-slide>
    </swiper>
    <swiper
      @swiper="setThumbsSwiper"
      :slides-per-view="5"
      watch-slides-visibility
      watch-slides-progress
      class="thumbs-swiper"
    >
      <swiper-slide v-for="n of projectsList.length" :virtualIndex="n" :key="n">
        <div class="thumbnail">
          <img :src="thumbnails[n - 1]" alt="" />
        </div>
      </swiper-slide>
    </swiper>
  </div>
</template>

<script>
import { Swiper, SwiperSlide } from "swiper/vue";
import {
  Autoplay,
  Navigation,
  Pagination,
  Thumbs,
  Mousewheel,
  A11y,
} from "swiper";

import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/autoplay";
import "swiper/css/thumbs";
import "swiper/css/mousewheel";

export default {
  name: "ProjectsCarousel",
  components: {
    Swiper,
    SwiperSlide,
  },
  props: ["projectsList"],
  data() {
    return {};
  },
  setup() {
    let swiperThumbs = ref(null);
    const thumbnails = [
      "https://ucarecdn.com/f218d322-4541-4506-9348-d538bdf7a5f1/",
      "https://ucarecdn.com/125366f3-6187-4d13-94ba-05e8795399c6/",
      "https://ucarecdn.com/9f3f8943-86e5-413a-840b-dc529a60d48b/",
      "https://ucarecdn.com/8ad222c1-29ed-4815-9f4e-fd384e673c0d/",
      "https://ucarecdn.com/9e5823e1-79d0-4013-acba-f3c4672111ca/",
    ];

    const setThumbsSwiper = (swiper) => {
      this.swiperThumbs = swiper;
    };

    return {
      swiperThumbs,
      setThumbsSwiper,
      thumbnails,
      modules: [Navigation, Pagination, Autoplay, Thumbs, Mousewheel, A11y],
    };
  },
  methods: {
    setThumbsSwiper(swiper) {
      this.swiperThumbs = swiper;
    },
  },
  computed: {},
  mounted() {},
};
</script>

<style language="postcss">
.swiper-button-next:after,
.swiper-button-prev:after {
  @apply text-pink-500 transition-all;
}

.swiper-pagination-bullet {
  @apply bg-pink-300 w-10 rounded hover:bg-pink-500 transition-all;
}

.swiper-pagination-bullet-active {
  @apply bg-light-accent  transition-all;
}

.swiper-slide .thumbnail {
  @apply scale-75 hover:scale-90 grayscale transition-all h-[100px] w-[200px] flex justify-center items-center cursor-pointer;
}

.thumbs-swiper .swiper-wrapper {
  @apply divide-x divide-gray-300 divide-dashed;
}

.swiper-slide-thumb-active .thumbnail {
  @apply scale-100 hover:scale-100 grayscale-0 bg-pink-50 rounded px-2 transition-all;
}
</style>
