// pages/aqua/index.vue
<template>
  <div class="divide-y divide-gray-50">
    <Html>
      <Head>
        <Link
          rel="canonical"
          :href="`https://fairdataihub.org${$route.path}`"
        />
        <Title>AQUA - Fair Data Innovations Hub</Title>
      </Head>
    </Html>

    <base-section data-aos="fade-in" class="py-10 pt-16 bg-white">
      <AquaHerosection></AquaHerosection>
    </base-section>

    <base-section data-aos="fade-in" class="py-10 bg-grey-50">
      <AboutAqua></AboutAqua>
    </base-section>

    <base-section data-aos="fade-in" class="py-10 bg-white">
      <AQUAToolsUsed></AQUAToolsUsed>
    </base-section>

    <base-section data-aos="fade-in" class="py-10 bg-grey-50">
      <AquaDevApproachFundingTeam></AquaDevApproachFundingTeam>
    </base-section>

    <base-section data-aos="fade-in" class="py-10 bg-white">
      <AquaPublications></AquaPublications>
    </base-section>
  </div>
</template>

<script>
import AquaHerosection from "~~/components/aqua/AquaHerosection.vue";
import AboutAqua from "~~/components/aqua/AboutAqua.vue";
import AQUAToolsUsed from "~~/components/aqua/AQUAToolsUsed.vue";
import AquaDevApproachFundingTeam from "~~/components/aqua/AquaDevApproachFundingTeam.vue";
import AquaPublications from "~~/components/aqua/AquaPublications.vue";

export default {
  layout: "default",
  scrollToTop: true,
  components: {
    AquaHerosection,
    AboutAqua,
    AQUAToolsUsed,
    AquaDevApproachFundingTeam,
    AquaPublications,
  },
  mounted() {
    window.scrollTo(0, 0);
  },
};
</script>

<style></style>

// src/pages/aqua.tsx
import Head from 'next/head';

import About from '@/components/aqua/about';
import Hero from '@/components/aqua/hero';
import Info from '@/components/aqua/info';
import Publications from '@/components/aqua/publications';
import Tools from '@/components/aqua/tools';

export default function Aqua() {
  return (
    <>
      <Head>
        <title>AQUA - Fair Data Innovations Hub</title>
        <meta property="og:title" content="AQUA - Fair Data Innovations Hub" />
        <meta name="twitter:title" content="AQUA - Fair Data Innovations Hub" />

        <link rel="canonical" href="https://fairdataihub.org/aqua" />
        <meta property="og:url" content="https://fairdataihub.org/aqua" />
        <meta name="twitter:url" content="https://fairdataihub.org/aqua" />

        <meta
          name="description"
          content="AQUA (Advanced Query Architecture for the SPARC Portal) an application that aims at improving the search capabilities of the SPARC Portal"
        />
        <meta
          property="og:description"
          content="AQUA (Advanced Query Architecture for the SPARC Portal) an application that aims at improving the search capabilities of the SPARC Portal"
        />
        <meta
          name="twitter:description"
          content="AQUA (Advanced Query Architecture for the SPARC Portal) an application that aims at improving the search capabilities of the SPARC Portal"
        />

        <meta
          property="og:image"
          content="https://fairdataihub.org/thumbnails/aqua.png"
        />
        <meta
          name="twitter:image"
          content="https://fairdataihub.org/thumbnails/aqua.png"
        />
      </Head>

      <section className="bg-white py-10 pt-16">
        <Hero />
      </section>

      <section className="bg-gray-50 py-10">
        <About />
      </section>

      <section className="bg-white py-10">
        <Tools />
      </section>

      <section className="bg-gray-50 py-10 ">
        <Info />
      </section>

      <section className="bg-white py-10 ">
        <Publications />
      </section>
    </>
  );
}
