// pages/cookiepolicy/index.vue
<template>
  <base-section class="">
    <Html>
      <Head>
        <Link
          rel="canonical"
          :href="`https://fairdataihub.org${$route.path}`"
        />
      </Head>
      <Title>Cookie Policy - Fair Data Innovations Hub</Title>
    </Html>

    <section
      class="text-black flex flex-col mx-auto max-w-screen-lg py-5 text-lg px-6 sm:px-6 lg:px-8"
    >
      <h1 class="heading">Cookie Policy for Fair Data Innovations Hub</h1>

      <h2 class="subheading">What Are Cookies?</h2>

      <p>
        As is common practice with almost all professional websites this site
        uses cookies, which are tiny files that are downloaded to your computer,
        to improve your experience. This page describes what information they
        gather, how we use it and why we sometimes need to store these cookies.
        We will also share how you can prevent these cookies from being stored
        however this may downgrade or 'break' certain elements of the sites
        functionality.
      </p>

      <p>
        For more information, please visit
        <a
          href="https://www.allaboutcookies.org/"
          rel="external nofollow noopener"
          target="_blank"
          class="text-url text-base"
          >AllAboutCookies.org</a
        >.
      </p>

      <h2 class="subheading">How We Use Cookies</h2>

      <p>
        We use cookies for a variety of reasons detailed below. Unfortunately in
        most cases there are no industry standard options for disabling cookies
        without completely disabling the functionality and features they add to
        this site. It is recommended that you leave on all cookies if you are
        not sure whether you need them or not in case they are used to provide a
        service that you use.
      </p>

      <h2 class="subheading">Disabling Cookies</h2>

      <!-- <p>
        If you prefer to avoid the use of cookies on the Website, first you must
        disable the use of cookies in your browser and then delete the cookies
        saved in your browser associated with this website. You may use this
        option for preventing the use of cookies at any time.
      </p>

      <p>
        If you do not accept our cookies, you may experience some inconvenience
        in your use of the Website and some features may not function properly.
      </p> -->

      <p>
        At the moment we do not have the functionality to disable cookies from
        the website. In order to prevent any tracking by third party analysis
        and measurement tools we use, please follow the steps provided below for
        your specific browser.
      </p>

      <h2 class="subheading">
        Find out how to manage cookies on popular browsers
      </h2>

      <div class="pl-8">
        <ul
          class="list-disc list-outside pb-3 my-1 text-base leading-7 text-gray-800"
        >
          <li>
            <a
              href="https://support.google.com/accounts/answer/61416"
              rel="external nofollow noopener"
              target="_blank"
              class="text-url text-base"
              >Google Chrome</a
            >
          </li>
          <li>
            <a
              href="https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences"
              rel="external nofollow noopener"
              target="_blank"
              class="text-url text-base"
              >Mozilla Firefox</a
            >
          </li>
          <li>
            <a
              href="https://support.apple.com/en-gb/guide/safari/sfri11471/mac"
              rel="external nofollow noopener"
              target="_blank"
              class="text-url text-base"
              >Apple Safari</a
            >
          </li>
          <li>
            <a
              href="https://support.microsoft.com/sr-latn-rs/help/4468242/microsoft-edge-browsing-data-and-privacy-microsoft-privacy"
              rel="external nofollow noopener"
              target="_blank"
              class="text-url text-base"
              >Microsoft Edge</a
            >
          </li>
          <li>
            <a
              href="https://support.microsoft.com/en-gb/help/17442/windows-internet-explorer-delete-manage-cookies"
              rel="external nofollow noopener"
              target="_blank"
              class="text-url text-base"
              >Microsoft Internet Explorer</a
            >
          </li>
          <li>
            <a
              href="https://help.opera.com/en/latest/web-preferences/#cookies"
              rel="external nofollow noopener"
              target="_blank"
              class="text-url text-base"
              >Opera</a
            >
          </li>
        </ul>
      </div>

      <p>
        To find information relating to other browsers, visit the browser
        developer's website.
      </p>

      <p>
        To opt-out of being tracked by Google Analytics across all websites,
        visit
        <a
          href="http://tools.google.com/dlpage/gaoptout"
          rel="external nofollow noopener"
          target="_blank"
          class="text-url text-base"
          >http://tools.google.com/dlpage/gaoptout</a
        >
      </p>

      <p>
        You can also visit the trade body representing these advertising
        platforms for more information:
        <a
          href="https://www.networkadvertising.org/choices/;"
          rel="external nofollow noopener"
          target="_blank"
          class="text-url text-base"
          >Network Advertising Initiative</a
        >.
      </p>

      <p>
        When you access third party sites on our Sites, or when you are reading
        integration or social media links, cookies can be created by the
        companies disseminating these links. These third parties may be able to
        use cookies in the context of Fair Data Innovations Hub's Services
        (partners or other third parties supplying content or services available
        on the Fair Data Innovations Hub site) and are responsible for the
        cookies they install, and it is their conditions on cookies which apply.
        For more information, you are advised to check the cookie policy
        directly on these third-party sites concerning their use of cookies.
      </p>

      <h2 class="subheading">The Cookies We Set</h2>

      <div class="pl-8">
        <ul
          class="list-disc list-outside pb-3 my-1 text-base leading-7 text-gray-800"
        >
          <li>
            <span class="italic"> Site preferences cookies </span> - In order to
            provide you with a great experience on this site we provide the
            functionality to set your preferences for how this site runs when
            you use it. In order to remember your preferences we need to set
            cookies so that this information can be called whenever you interact
            with a page is affected by your preferences.
          </li>
        </ul>
      </div>

      <h2 class="subheading">Third Party Cookies</h2>

      <p>
        In some special cases we also use cookies provided by trusted third
        parties. The following section details which third party cookies you
        might encounter through this site.
      </p>

      <div class="pl-8">
        <ul
          class="list-disc list-outside pb-3 my-1 text-base leading-7 text-gray-800"
        >
          <li>
            This site uses Google Analytics which is one of the most widespread
            and trusted analytics solution on the web for helping us to
            understand how you use the site and ways that we can improve your
            experience. These cookies may track things such as how long you
            spend on the site and the pages that you visit so we can continue to
            produce engaging content. For more information on Google Analytics
            cookies, see the official
            <a
              href="https://policies.google.com/privacy?hl=en-US"
              target="_blank"
              rel="noopener"
              class="text-url text-base"
            >
              Google Analytics page </a
            >.
          </li>

          <li>
            Third party analytics are used to track and measure usage of this
            site so that we can continue to produce engaging content. These
            cookies may track things such as how long you spend on the site or
            pages you visit which helps us to understand how we can improve the
            site for you.
          </li>

          <li>
            From time to time we test new features and make subtle changes to
            the way that the site is delivered. When we are still testing new
            features these cookies may be used to ensure that you receive a
            consistent experience whilst on the site whilst ensuring we
            understand which optimisations our users appreciate the most.
          </li>

          <li>
            As we sell products it's important for us to understand statistics
            about how many of the visitors to our site actually make a purchase
            and as such this is the kind of data that these cookies will track.
            This is important to you as it means that we can accurately make
            business predictions that allow us to monitor our advertising and
            product costs to ensure the best possible price.
          </li>

          <li>
            We also use social media buttons and/or plugins on this site that
            allow you to connect with your social network in various ways. For
            these to work the following social media sites including Twitter,
            Facebook, Instagram, etc., will set cookies through our site which
            may be used to enhance your profile on their site or contribute to
            the data they hold for various purposes outlined in their respective
            privacy policies.
          </li>
        </ul>
      </div>

      <h2 class="subheading">Questions and complaints</h2>

      <p>
        Please feel free to contact us if you have any questions or complaints
        about Fair Data Innovation Hub's Cookie Policy.
      </p>

      <p>
        <strong> Address: </strong> 11107 Roselle St. Ste #211 San Diego, CA
        92121
      </p>

      <p>
        <strong> Contact form: </strong>
        <NuxtLink to="/contact-us" class="text-url text-base">
          https://fairdataihub.org/contact-us
        </NuxtLink>
      </p>

      <p>
        <strong> Email: </strong>
        <a href="mailto:info@fairdataihub.org" class="text-url text-base">
          info@fairdataihub.org
        </a>
      </p>
    </section>
  </base-section>
</template>

<script>
export default {
  layout: "default",
  scrollToTop: true,
  mounted() {
    window.scrollTo(0, 0);
  },
};
</script>

<style lang="postcss" scoped>
.heading {
  @apply mb-3 mt-4 font-extrabold tracking-tight text-4xl;
}

.subheading {
  @apply mb-3 mt-6 font-bold tracking-tight text-3xl;
}

p {
  @apply my-1 text-base leading-7 text-gray-800 font-normal;
}
</style>

// src/pages/cookiepolicy.tsx
import Head from 'next/head';

import Link from 'next/link';

export default function CookiePolicy() {
  return (
    <div>
      <Head>
        <title>Cookie Policy - Fair Data Innovations Hub</title>
        <meta
          property="og:title"
          content="Cookie Policy - Fair Data Innovations Hub"
        />
        <meta
          property="twitter:title"
          content="Cookie Policy - Fair Data Innovations Hub"
        />

        <link rel="canonical" href="https://fairdataihub.org/cookiepolicy" />
        <meta
          property="og:url"
          content="https://fairdataihub.org/cookiepolicy"
        />
        <meta
          property="twitter:url"
          content="https://fairdataihub.org/cookiepolicy"
        />

        <meta
          name="description"
          content="View the Cookie Policy of fairdataihub.org"
        />
        <meta
          property="og:description"
          content="View the Cookie Policy of fairdataihub.org"
        />
        <meta
          property="twitter:description"
          content="View the Cookie Policy of fairdataihub.org"
        />

        <meta
          property="og:image"
          content="https://fairdataihub.org/thumbnails/index.png"
        />
        <meta
          property="twitter:image"
          content="https://fairdataihub.org/thumbnails/index.png"
        />
      </Head>

      <main>
        <section className="mx-auto flex max-w-screen-lg flex-col px-6 py-5 text-lg text-black sm:px-6 lg:px-8">
          <h1 className="heading">Cookie Policy</h1>

          <h2 className="subheading">What Are Cookies?</h2>

          <p className="content">
            As is common practice with almost all professional websites this
            site uses cookies, which are tiny files that are downloaded to your
            computer, to improve your experience. This page describes what
            information they gather, how we use it and why we sometimes need to
            store these cookies. We will also share how you can prevent these
            cookies from being stored however this may downgrade or
            &apos;break&apos; certain elements of the sites functionality.
          </p>

          <p className="content">
            For more information, please visit
            <a
              href="https://www.allaboutcookies.org/"
              rel="noreferrer"
              target="_blank"
              className="text-url text-base"
            >
              &nbsp;AllAboutCookies.org
            </a>
            .
          </p>

          <h2 className="subheading">How We Use Cookies</h2>

          <p className="content">
            We use cookies for a variety of reasons detailed below.
            Unfortunately in most cases there are no industry standard options
            for disabling cookies without completely disabling the functionality
            and features they add to this site. It is recommended that you leave
            on all cookies if you are not sure whether you need them or not in
            case they are used to provide a service that you use.
          </p>

          <h2 className="subheading">Disabling Cookies</h2>

          {/* <p className='content'>
        If you prefer to avoid the use of cookies on the Website, first you must
        disable the use of cookies in your browser and then delete the cookies
        saved in your browser associated with this website. You may use this
        option for preventing the use of cookies at any time.
      </p>
      <p className='content'>
        If you do not accept our cookies, you may experience some inconvenience
        in your use of the Website and some features may not function properly.
      </p>  */}

          <p className="content">
            At the moment we do not have the functionality to disable cookies
            from the website. In order to prevent any tracking by third party
            analysis and measurement tools we use, please follow the steps
            provided below for your specific browser.
          </p>

          <h2 className="subheading">
            Find out how to manage cookies on popular browsers
          </h2>

          <div className="pl-8">
            <ul className="my-1 list-outside list-disc pb-3 text-base leading-7 text-gray-800">
              <li>
                <a
                  href="https://support.google.com/accounts/answer/61416"
                  rel="noreferrer"
                  target="_blank"
                  className="text-url text-base"
                >
                  Google Chrome
                </a>
              </li>
              <li>
                <a
                  href="https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences"
                  rel="noreferrer"
                  target="_blank"
                  className="text-url text-base"
                >
                  Mozilla Firefox
                </a>
              </li>
              <li>
                <a
                  href="https://support.apple.com/en-gb/guide/safari/sfri11471/mac"
                  rel="noreferrer"
                  target="_blank"
                  className="text-url text-base"
                >
                  Apple Safari
                </a>
              </li>
              <li>
                <a
                  href="https://support.microsoft.com/sr-latn-rs/help/4468242/microsoft-edge-browsing-data-and-privacy-microsoft-privacy"
                  rel="noreferrer"
                  target="_blank"
                  className="text-url text-base"
                >
                  Microsoft Edge
                </a>
              </li>
              <li>
                <a
                  href="https://support.microsoft.com/en-gb/help/17442/windows-internet-explorer-delete-manage-cookies"
                  rel="noreferrer"
                  target="_blank"
                  className="text-url text-base"
                >
                  Microsoft Internet Explorer
                </a>
              </li>
              <li>
                <a
                  href="https://help.opera.com/en/latest/web-preferences/#cookies"
                  rel="noreferrer"
                  target="_blank"
                  className="text-url text-base"
                >
                  Opera
                </a>
              </li>
            </ul>
          </div>

          <p className="content">
            To find information relating to other browsers, visit the browser
            developer&apos;s website.
          </p>

          <p className="content">
            To opt-out of being tracked by Google Analytics across all websites,
            visit
            <a
              href="http://tools.google.com/dlpage/gaoptout"
              rel="noreferrer"
              target="_blank"
              className="text-url text-base"
            >
              &nbsp;http://tools.google.com/dlpage/gaoptout
            </a>
          </p>

          <p className="content">
            You can also visit the trade body representing these advertising
            platforms for more information:
            <a
              href="https://www.networkadvertising.org/choices/;"
              rel="noreferrer"
              target="_blank"
              className="text-url text-base"
            >
              &nbsp;Network Advertising Initiative
            </a>
            .
          </p>

          <p className="content">
            When you access third party sites on our Sites, or when you are
            reading integration or social media links, cookies can be created by
            the companies disseminating these links. These third parties may be
            able to use cookies in the context of Fair Data Innovations
            Hub&apos;s Services (partners or other third parties supplying
            content or services available on the Fair Data Innovations Hub site)
            and are responsible for the cookies they install, and it is their
            conditions on cookies which apply. For more information, you are
            advised to check the cookie policy directly on these third-party
            sites concerning their use of cookies.
          </p>

          <h2 className="subheading">The Cookies We Set</h2>

          <div className="pl-8">
            <ul className="my-1 list-outside list-disc pb-3 text-base leading-7 text-gray-800">
              <li>
                <span className="italic"> Site preferences cookies </span> - In
                order to provide you with a great experience on this site we
                provide the functionality to set your preferences for how this
                site runs when you use it. In order to remember your preferences
                we need to set cookies so that this information can be called
                whenever you interact with a page is affected by your
                preferences.
              </li>
            </ul>
          </div>

          <h2 className="subheading">Third Party Cookies</h2>

          <p className="content">
            In some special cases we also use cookies provided by trusted third
            parties. The following section details which third party cookies you
            might encounter through this site.
          </p>

          <div className="pl-8">
            <ul className="my-1 list-outside list-disc pb-3 text-base leading-7 text-gray-800">
              <li>
                This site uses Google Analytics which is one of the most
                widespread and trusted analytics solution on the web for helping
                us to understand how you use the site and ways that we can
                improve your experience. These cookies may track things such as
                how long you spend on the site and the pages that you visit so
                we can continue to produce engaging content. For more
                information on Google Analytics cookies, see the official
                <a
                  href="https://policies.google.com/privacy?hl=en-US"
                  target="_blank"
                  rel="noreferrer"
                  className="text-url text-base"
                >
                  &nbsp;Google Analytics page
                </a>
                .
              </li>

              <li>
                Third party analytics are used to track and measure usage of
                this site so that we can continue to produce engaging content.
                These cookies may track things such as how long you spend on the
                site or pages you visit which helps us to understand how we can
                improve the site for you.
              </li>

              <li>
                From time to time we test new features and make subtle changes
                to the way that the site is delivered. When we are still testing
                new features these cookies may be used to ensure that you
                receive a consistent experience whilst on the site whilst
                ensuring we understand which optimisations our users appreciate
                the most.
              </li>

              <li>
                As we sell products it&apos;s important for us to understand
                statistics about how many of the visitors to our site actually
                make a purchase and as such this is the kind of data that these
                cookies will track. This is important to you as it means that we
                can accurately make business predictions that allow us to
                monitor our advertising and product costs to ensure the best
                possible price.
              </li>

              <li>
                We also use social media buttons and/or plugins on this site
                that allow you to connect with your social network in various
                ways. For these to work the following social media sites
                including Twitter, Facebook, Instagram, etc., will set cookies
                through our site which may be used to enhance your profile on
                their site or contribute to the data they hold for various
                purposes outlined in their respective privacy policies.
              </li>
            </ul>
          </div>

          <h2 className="subheading">Questions and complaints</h2>

          <p className="content">
            Please feel free to contact us if you have any questions or
            complaints about Fair Data Innovation Hub&apos;s Cookie Policy.
          </p>

          <p className="content">
            <strong> Address: </strong> 11107 Roselle St. Ste #211 San Diego, CA
            92121
          </p>

          <p className="content">
            <strong> Contact form: </strong>
            <Link href="/contact-us" passHref>
              <span className="text-url cursor-pointer text-base">
                https://fairdataihub.org/contact-us
              </span>
            </Link>
          </p>

          <p className="content">
            <strong> Email: </strong>
            <a
              href="mailto:info@fairdataihub.org"
              className="text-url text-base"
            >
              info@fairdataihub.org
            </a>
          </p>
        </section>
      </main>
    </div>
  );
}
