// components/home/AboutUs.vue
<template>
  <div
    class="container max-w-screen-lg px-6 py-0 mx-auto sm:pt-6 sm:pb-4"
    :id="id"
  >
    <div class="items-center justify-center sm:flex">
      <div
        class="flex items-center justify-center w-full p-8 mt-6 lg:mt-0 lg:w-1/2"
      >
        <LottieComponentVue :animationData="TeamData" />
      </div>

      <div class="w-full h-full p-2 lg:w-1/2">
        <h1
          class="w-full py-4 pt-6 text-4xl subpixel-antialiased font-black text-left md:py-3 sm:text-3xl md:text-3xl lg:text-4xl sm:text-center"
        >
          About Us
        </h1>

        <p
          class="w-full mt-2 mb-6 text-xl text-left text-black md:my-2 font-asap sm:text-center sm:text-base md:text-lg lg:text-xl"
        >
          FAIR Data Innovations Hub is a division of the California Medical
          Innovations Institute (CalMI<sup>2</sup>), a non profit biomedical
          research organization located in San Diego, California. We have a
          multidisciplinary team of enthusiasts about FAIR Data practices and
          software development.
        </p>

        <div class="flex justify-center w-full py-5">
          <NuxtLink to="/team">
            <button
              type="button"
              class="px-6 py-4 text-base font-semibold text-center text-white transition duration-200 ease-in-out bg-black rounded-md w-max-content ring-2 ring-offset-2 ring-transparent hover:ring-pink-600 focus:ring-pink-600"
            >
              Meet our team
            </button>
          </NuxtLink>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import LottieComponentVue from "../lottie/LottieComponent.vue";

import TeamData from "../../assets/lotties/team.json";

export default {
  name: "AboutUs",
  props: ["id"],
  components: {
    LottieComponentVue,
  },
  data() {
    return {
      TeamData,
    };
  },
};
</script>

<style></style>

// src/components/home/aboutUs.tsx
import Link from "next/link";

import LottieAnimation from "@/components/lotties";

import teamLottie from "../../assets/lotties/team.json";

export default function AboutUs() {
  return (
    <div className="container mx-auto max-w-screen-lg px-6 py-0 sm:pt-6 sm:pb-4">
      <div className="items-center justify-center md:flex">
        <div className="mt-6 flex w-full items-center justify-center p-8 lg:mt-0 lg:w-1/2">
          <LottieAnimation
            animationData={teamLottie}
            width={400}
            height={400}
          />
        </div>

        <div className="h-full w-full p-2 lg:max-w-2xl">
          <h1 className="w-full py-4 pt-6 text-left text-4xl font-black subpixel-antialiased sm:text-center sm:text-3xl md:py-3 md:text-3xl lg:text-4xl">
            About Us
          </h1>

          <p className=" mt-2 mb-6 w-full text-left font-asap text-xl text-black sm:text-center  md:my-2 md:text-lg">
            FAIR Data Innovations Hub is a division of the California Medical
            Innovations Institute (CalMI<sup>2</sup>), a non profit biomedical
            research organization located in San Diego, California. We have a
            multidisciplinary team of enthusiasts about FAIR Data practices and
            software development.
          </p>
          <div className="flex w-full justify-center py-5">
            <a
              href="https://calmi2.org/"
              target="_blank"
              className="hidden"
              rel="noreferrer"
            ></a>
            <Link href="/team" passHref>
              <button
                type="button"
                className="w-max-content rounded-md border-none bg-black px-6 py-4 text-center text-base font-semibold text-white ring-2 ring-transparent ring-offset-2 transition duration-200 ease-in-out hover:ring-pink-600 focus:ring-pink-600"
              >
                Meet our team
              </button>
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
