// src/components/HomePage/ProjectsCarousel.vue
<template>
  <div class="w-full max-w-screen-xl mx-auto h-auto pt-1 pb-3">
    <div class="flex flex-col justify-center items-center mb-4">
      <h2
        class="
          my-2
          leading-8
          font-extrabold
          tracking-tight
          text-gray-900
          dark:text-white
          text-4xl
          sm:text-4xl
          text-center
        "
      >
        Current Projects
      </h2>
      <p
        class="
          w-full
          max-w-2xl
          text-xl text-black
          dark:text-white
          text-center
          p-2
        "
      >
        These are the projects we are working on at the moment.
      </p>
    </div>
    <!-- Slides container -->
    <vueper-slides
      :bullets="true"
      :arrows="true"
      :touchable="false"
      :class="`no-shadow`"
      autoplay
      :pause-on-hover="true"
      :fixed-height="`55vh`"
    >
      <vueper-slide>
        <template v-slot:content>
          <section
            class="text-gray-600 w-full h-full body-font px-5 flex items-center"
          >
            <div
              class="
                container
                mx-auto
                flex
                px-5
                sm:mb-2
                flex-col-reverse
                md:flex-row md:justify-evenly
                items-center
              "
            >
              <!-- text div -->
              <div
                class="
                  md:w-7/12
                  flex flex-col
                  my-1
                  sm:mb-16
                  md:mb-0
                  items-center
                  text-center
                "
              >
                <h3
                  class="
                    font-sans font-semibold
                    text-3xl
                    md:text-2xl
                    lg:text-3xl
                    w-full
                    mb-1
                    sm:mb-4
                    text-left
                    sm:text-center
                    text-black
                    dark:text-white
                  "
                >
                  SODA for SPARC
                </h3>

                <p
                  class="
                    w-full
                    mb-4
                    sm:mb-8
                    text-left
                    sm:text-center
                    text-base
                    md:text-base
                    lg:text-lg
                    font-sans
                    text-black
                    dark:text-white
                  "
                >
                  SODA (Software to Organize Data Automatically) for SPARC is a
                  desktop software intended to facilitate the data organization
                  and submission process for SPARC investigators and thus
                  promote the FAIR Data Principles.
                </p>
                <div class="w-full flex justify-center">
                  <!-- <a
              href="https://github.com/bvhpatel/SODA#Downloading-soda"
              target="_blank"
            >
              <button
                class="
                  hidden
                  sm:inline-flex
                  text-white
                  border-0
                  py-2
                  px-6
                  focus:outline-none
                  bg-indigo-500
                  hover:bg-indigo-600
                  rounded
                  text-lg
                  transition
                "
              >
                Download now (github)
              </button>
            </a> -->
                  <router-link to="/sodasparc/docs/Download-soda">
                    <button
                      class="
                        hidden
                        sm:inline-flex
                        text-white
                        bg-primary
                        hover:bg-blue-600
                        border-0
                        py-2
                        px-6
                        focus:outline-none
                        rounded
                        text-lg
                        md:text-base
                        lg:text-lg
                        transition
                      "
                    >
                      Download now
                    </button>
                  </router-link>
                  <router-link to="/sodasparc">
                    <button
                      class="
                        sm:ml-4
                        inline-flex
                        text-white
                        bg-primary
                        hover:bg-blue-600
                        border-0
                        py-2
                        px-6
                        focus:outline-none
                        rounded
                        text-lg
                        md:text-base
                        lg:text-lg
                        transition
                      "
                    >
                      Learn more about SODA for SPARC
                    </button>
                  </router-link>
                </div>
              </div>
              <!-- image div -->
              <div
                class="
                  lg:max-w-lg
                  md:w-3/12
                  w-5/6
                  py-4
                  my-2
                  sm:py-0
                  flex
                  justify-center
                "
              >
                <img
                  class="
                    object-cover object-center
                    rounded
                    sm:h-36
                    md:h-40
                    lg:h-auto
                    sm:w-36
                    md:w-40
                    lg:w-auto
                  "
                  alt="SODA for SPARC logo"
                  src="https://github.com/bvhpatel/SODA/raw/master/src/assets/img/logo-can1024-grey-circle.png"
                />
              </div>
            </div>
          </section>
        </template>
      </vueper-slide>
      <vueper-slide>
        <template v-slot:content>
          <section
            class="text-gray-600 w-full h-full body-font px-5 flex items-center"
          >
            <div
              class="
                container
                mx-auto
                flex
                px-5
                sm:mb-2
                flex-col-reverse
                md:flex-row md:justify-evenly
                items-center
              "
            >
              <!-- text div -->
              <div
                class="
                  md:w-7/12
                  flex flex-col
                  my-1
                  sm:mb-16
                  md:mb-0
                  items-center
                  text-center
                "
              >
                <h3
                  class="
                    font-sans font-semibold
                    text-3xl
                    md:text-2xl
                    lg:text-3xl
                    w-full
                    mb-1
                    sm:mb-4
                    text-left
                    sm:text-center
                    text-black
                    dark:text-white
                  "
                >
                  SODA for COVID
                </h3>

                <p
                  class="
                    w-full
                    mb-4
                    sm:mb-8
                    text-left
                    sm:text-center
                    text-base
                    md:text-base
                    lg:text-lg
                    font-sans
                    text-black
                    dark:text-white
                  "
                >
                  SODA (Software to Organize Data Automatically) for SPARC is a
                  desktop software intended to facilitate the data organization
                  and submission process for SPARC investigators and thus
                  promote the FAIR Data Principles.
                </p>
                <div class="w-full flex justify-center">
                  <!-- <a
              href="https://github.com/bvhpatel/SODA#Downloading-soda"
              target="_blank"
            >
              <button
                class="
                  hidden
                  sm:inline-flex
                  text-white
                  border-0
                  py-2
                  px-6
                  focus:outline-none
                  bg-indigo-500
                  hover:bg-indigo-600
                  rounded
                  text-lg
                  transition
                "
              >
                Download now (github)
              </button>
            </a> -->
                  <router-link to="/sodasparc/docs/Download-soda">
                    <button
                      class="
                        hidden
                        sm:inline-flex
                        text-white
                        bg-primary
                        hover:bg-blue-600
                        border-0
                        py-2
                        px-6
                        focus:outline-none
                        rounded
                        text-base
                        md:text-base
                        lg:text-lg
                        transition
                      "
                    >
                      Download now
                    </button>
                  </router-link>
                  <router-link to="/sodasparc">
                    <button
                      class="
                        sm:ml-4
                        inline-flex
                        text-white
                        bg-primary
                        hover:bg-blue-600
                        border-0
                        py-2
                        px-6
                        focus:outline-none
                        rounded
                        text-lg
                        md:text-base
                        lg:text-lg
                        transition
                      "
                    >
                      Learn more about SODA for SPARC
                    </button>
                  </router-link>
                </div>
              </div>
              <!-- image div -->
              <div
                class="
                  lg:max-w-lg
                  md:w-3/12
                  w-5/6
                  py-4
                  my-2
                  sm:py-0
                  flex
                  justify-center
                "
              >
                <img
                  class="
                    object-cover object-center
                    rounded
                    sm:h-36
                    md:h-40
                    lg:h-auto
                    sm:w-36
                    md:w-40
                    lg:w-auto
                  "
                  alt="SODA for SPARC logo"
                  src="https://github.com/bvhpatel/SODA/raw/master/src/assets/img/logo-can1024-grey-circle.png"
                />
              </div>
            </div>
          </section>
        </template>
      </vueper-slide>
    </vueper-slides>
  </div>
</template>

<script>
import { VueperSlides, VueperSlide } from "vueperslides";
import "vueperslides/dist/vueperslides.css";
// import ProjectCard from "./ProjectCard.vue";

export default {
  name: "ProjectsCarousel",
  components: {
    VueperSlides,
    VueperSlide,
    // ProjectCard,
  },
  data() {
    return {
      sodaForSPARCData: [
        { name: "Windows Installer", href: "/sodasparc-windowsinstaller" },
        { name: "macOS Installer", href: "/sodasparc-macosinstaller" },
        { name: "Linux Installer", href: "/sodasparc-linuxinstaller" },
      ],
    };
  },
  methods: {},
};
</script>

<style>
.vueperslides__bullet .default {
  background-color: rgba(0, 0, 0, 0.3);
  border: none;
  box-shadow: none;
  transition: 0.3s;
  width: 16px;
  height: 16px;
}

.vueperslides__bullets {
  margin-top: 20px;
  padding-top: 20px;
}

.vueperslides__bullet--active .default {
  background-color: #42b983;
}

.vueperslides__bullet span {
  display: block;
  color: #fff;
  font-size: 10px;
  opacity: 0.8;
}

.vueperslides__arrow {
  color: purple;
}
</style>

// src/components/home/projectsCarousel.tsx
import { useState } from 'react';
import { Swiper, SwiperSlide } from 'swiper/react';
import { Autoplay, Navigation, Pagination, Thumbs, A11y } from 'swiper';
import Link from 'next/link';
import Image from 'next/image';

import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/autoplay';
import 'swiper/css/thumbs';

export default function ProjectsCarousel() {
  const thumbnails = [
    {
      src: `/images/carousel/sodasparc.png`,
      alt: `Navigate to SODA for SPARC card`,
      width: `150`,
      height: `50`,
    },
    {
      src: `/images/carousel/knowmore.png`,
      alt: `Navigate to Know More card`,
      width: `150`,
      height: `30`,
    },
    {
      src: `/images/carousel/sparclink.png`,
      alt: `Navigate to SPARClink card`,
      width: `150`,
      height: `40`,
    },
    {
      src: `/images/carousel/aqua.png`,
      alt: `Navigate to Aqua card`,
      width: `150`,
      height: `85`,
    },
    {
      src: `/images/carousel/sodacovid.png`,
      alt: `Navigate to FAIRshare card`,
      width: `150`,
      height: `50`,
    },
  ];

  const projectsList = [
    {
      name: `SODA for SPARC`,
      imageUrl: `/images/carousel/sodasparc.png`,
      imageWidth: `320`,
      imageHeight: `103`,
      description: `SODA (Software to Organize Data Automatically) for SPARC is a desktop software intended to facilitate the data organization and submission process for SPARC investigators according to the FAIR SPARC data standards.`,
      page: `/sodaforsparc`,
    },
    {
      name: `KnowMore`,
      imageUrl: `/images/carousel/knowmore.png`,
      imageWidth: `320`,
      imageHeight: `68`,
      description: `KnowMore is an automated knowledge discovery tool that allows users of the portal to visualize, in just a few clicks, potential similarities, differences, and connections between multiple SPARC datasets of their choice.`,
      page: `/knowmore`,
    },
    {
      name: `SPARClink`,
      imageUrl: `/images/carousel/sparclink.png`,
      imageWidth: `320`,
      imageHeight: `80`,
      description: `SPARClink is a system that queries publications using open source tools and platforms and create an interactable visualization that showcases the impact that SPARC and their FAIR data practices have in advancing the field of bioelectronic medicine.`,
      page: `/sparclink`,
    },
    {
      name: `AQUA`,
      imageUrl: `/images/carousel/aqua.png`,
      imageWidth: `320`,
      imageHeight: `177`,
      description: `AQUA (Advanced QUery Architecture for the SPARC Portal) improves the SPARC Portal by making the search engine smarter at understanding user search keywords, enhancing the result display, and providing users with better result filtering and sorting options.`,
      page: `/aqua`,
    },
    {
      name: `FAIRshare`,
      imageUrl: `/images/carousel/sodacovid-single.png`,
      imageWidth: `320`,
      imageHeight: `100`,
      description: `FAIRshare is a cross-platform desktop software that allows researchers to easily organize and share their COVID-19 related research data according to applicable FAIR guidelines.`,
      page: `/fairshare`,
    },
  ];

  const [SwiperThumbs, setSwiperThumbs] = useState(null);

  return (
    <>
      <section>
        <div className="mx-auto h-auto w-full max-w-screen-lg px-4 pt-1 pb-3">
          <div className="mb-4 flex flex-col items-center justify-center">
            <h2 className="my-2 text-center text-4xl font-extrabold tracking-tight sm:text-4xl">
              Current Projects
            </h2>
            <p className="w-full max-w-2xl text-center font-asap text-xl">
              These are the projects we are working on at the moment:
            </p>
          </div>

          <Swiper
            modules={[Navigation, Pagination, Autoplay, Thumbs, A11y]}
            slidesPerView={1}
            navigation
            setWrapperSize={true}
            grabCursor={true}
            loop={true}
            autoplay={{
              delay: 6000,
              pauseOnMouseEnter: true,
              disableOnInteraction: false,
            }}
            mousewheel={{ releaseOnEdges: true }}
            thumbs={{ swiper: SwiperThumbs }}
            className="h-full"
          >
            {projectsList.map((project, index) => (
              <SwiperSlide
                key={index}
                className="my-auto flex h-full items-center justify-center py-10"
              >
                <section className="mx-10 my-auto flex h-full w-4/5 flex-row items-center justify-center rounded-lg px-5 py-10 text-gray-600 shadow-xl">
                  <div className="container mx-auto flex h-full flex-col items-center justify-center">
                    <div className="relative my-5 flex flex-row items-center justify-center sm:py-0 lg:max-w-lg">
                      <Image
                        className="relative"
                        src={project.imageUrl}
                        alt={project.name + ` logo`}
                        width={project.imageWidth}
                        height={project.imageHeight}
                      />
                    </div>
                    <div className="my-4 flex h-full flex-col items-center text-center sm:mb-16 md:mb-0">
                      <p className="w-full text-left font-asap text-base text-black sm:text-center md:text-base lg:text-lg">
                        {project.description}
                      </p>

                      <div className="flex w-full justify-center py-4">
                        <Link href={project.page} passHref>
                          <button className="inline-flex rounded border-0 bg-black px-6 py-2 text-lg text-white ring-2 ring-transparent ring-offset-2 transition hover:ring-pink-600 focus:outline-none focus:ring-pink-600 sm:ml-4 md:text-base lg:text-lg">
                            Learn more about {project.name}
                          </button>
                        </Link>
                      </div>
                    </div>
                  </div>
                </section>
              </SwiperSlide>
            ))}
          </Swiper>
          <Swiper
            slidesPerView={5}
            watchSlidesProgress={true}
            className="thumbs-swiper hidden sm:block"
            // @ts-expect-error will fix this later
            onSwiper={(swiper) => setSwiperThumbs(swiper)}
          >
            {thumbnails.map((thumbnail, index) => (
              <SwiperSlide virtualIndex={index} key={index}>
                <div className="thumbnail relative h-max w-max">
                  <Image
                    className="px-3 py-2"
                    src={thumbnail.src}
                    alt={thumbnail.alt}
                    width={thumbnail.width}
                    height={thumbnail.height}
                  />
                </div>
              </SwiperSlide>
            ))}
          </Swiper>
        </div>
      </section>
    </>
  );
}
