// src/pages/404.tsx
import Link from 'next/link';

import LottieAnimation from '@/components/lotties';

import heroLottie from '../assets/lotties/404.json';

export default function Hero() {
  return (
    <section className="hero">
      <div className="container mx-auto max-w-screen-lg px-6 py-8">
        <div className="flex flex-col items-center justify-center md:flex md:flex-row">
          <div className="mt-6 hidden w-full items-center justify-center p-5 md:flex lg:mt-0 lg:w-1/2 lg:p-2">
            <LottieAnimation
              animationData={heroLottie}
              width={500}
              height={500}
            />
          </div>
          <div className="mt-6 flex w-full items-center justify-center p-5 md:hidden lg:mt-0 lg:w-1/2 lg:p-2">
            <LottieAnimation
              animationData={heroLottie}
              width={400}
              height={400}
            />
          </div>

          <div className="w-full p-2 lg:w-1/2 lg:max-w-lg">
            <h1 className="w-full text-left text-4xl font-black sm:text-3xl md:py-3 md:text-4xl lg:text-5xl">
              Oops!
            </h1>

            <p className="mt-2 w-full text-xl font-normal text-black sm:mt-0 sm:text-base md:text-lg lg:text-xl">
              The page you are looking for might have been removed, had its name
              changed or is temporarily unavailable.
            </p>

            <Link href="/" passHref>
              <button
                type="button"
                className="hover:border-light-accent hover:text-accent my-3 rounded-lg border-2 border-black bg-transparent p-3 text-center text-base font-semibold text-black transition-all"
              >
                Go to Homepage
              </button>
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
}

// pages/404.vue
<template>
  <main class="relative h-screen overflow-hidden bg-white">
    <div
      class="container z-10 flex items-center justify-between w-full h-screen px-3 pt-32 mx-auto md:pt-0"
    >
      <div
        class="container flex flex-col items-center justify-end px-6 mx-auto"
      >
        <div class="block w-full max-w-md mx-auto mb-16 md:mt-0 lg:max-w-2xl">
          <LottieComponentVue :animationData="ErrorData" />
        </div>
        <div
          class="flex flex-col items-center w-full text-center md:mb-8 lg:text-left"
        >
          <h1
            class="my-10 mt-12 font-sans text-4xl font-light text-center text-gray-700 lg:text-5xl md:mt-0"
          >
            This page isn't available
          </h1>
          <NuxtLink to="/">
            <button
              type="button"
              class="px-6 py-4 text-base font-semibold text-center text-white transition duration-200 ease-in-out bg-black rounded-md w-max-content ring-2 ring-offset-2 ring-transparent hover:ring-pink-600 focus:ring-pink-600"
            >
              Go back home
            </button>
          </NuxtLink>
        </div>
      </div>
    </div>
  </main>
</template>

<script>
import LottieComponentVue from "~~/components/lottie/LottieComponent.vue";

import ErrorData from "../assets/lotties/error.json";

export default {
  components: {
    LottieComponentVue,
  },
  data() {
    return {
      ErrorData,
    };
  },
};
</script>

<style></style>
